Реализовал основной функционал ТЗ-13
IgorShurov/java-shareit pull request #1
Opened 2024-01-30 20:26 UTC by IgorShurov

2024-01-31 07:11 UTC, Frilock requested changes
Добрый день, оставил комментарии в коде:
1. Отсутствует валидация входных данных
2. Инжектите интерфейсы, там где это возможно, а не реализации
3. С части мапперов можно убрать аннотацию компонент и использовать их статик методы
4. Упрощение части методов

2024-01-31 07:11 UTC, Frilock commented on pom.xml
> +            <version>3.12.0</version>
Версию в properties

2024-01-31 07:11 UTC, Frilock commented on src/main/java/ru/practicum/shareit/exception/UserValidationException.java
> +public class UserValidationException extends ValidationException {
Вы под каждую ентити будете делать свое исключение? А если их 10 или 100 будет? Проще класс передавать

2024-01-31 07:11 UTC, Frilock commented on src/main/java/ru/practicum/shareit/handler/ErrorResponse.java
> +    private final String error;
Вообще не очень понимаю для чего этот класс вам? Просто строковое поле =)

2024-01-31 07:11 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/InMemoryItemStorage.java
> +                    .filter(item -> item.getName().toLowerCase().contains(text) ||
Лучше StringUtils.equalsIgnoreCase

2024-01-31 07:11 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/InMemoryItemStorage.java
> +            item.setName(items.get(item.getId()).getName());
items.get повторяется 3 раза - вынесите в переменную и 
данную конструкцию можно заменить на Optional.ofNullable(...).ifPresent(...) будет выглядеть компактнее

2024-01-31 07:11 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    private final ItemServiceImpl itemService;
Инжектить правильнее интерфейс, а не реализацию

2024-01-31 07:11 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +    private String name;
А не хотите валидацию на поля добавить?

2024-01-31 07:11 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/ItemMapper.java
> +@Component
А зачем этот маппер делать компонентом? Сделайте статик методы и просто их вызывайте

2024-01-31 07:11 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +    public List<ItemDto> getItemsByOwner(Long ownerId) {
Отсутствуют owerride над методами

2024-01-31 07:11 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +            throw new ItemNotFoundException("User does not have such a item!");
Добавляйте уникальные детали в ошибку, например, ид с которым не нашли или еще что то

2024-01-31 07:11 UTC, Frilock commented on src/main/java/ru/practicum/shareit/user/InMemoryUserStorage.java
> +            user.setName(users.get(user.getId()).getName());
Аналогично

2024-01-31 07:11 UTC, Frilock commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    private final UserServiceImpl userService;
Аналогично

2024-01-31 07:11 UTC, Frilock commented on src/main/java/ru/practicum/shareit/user/UserMapper.java
> +@Component
Аналогично

2024-01-31 23:40 UTC, IgorShurov commented on src/main/java/ru/practicum/shareit/item/InMemoryItemStorage.java
> +            item.setName(items.get(item.getId()).getName());
.ifPresent не получается использовать (либо я не понимаю как его использовать), так как у меня item.getName() == null, а ifPresent эквивалентно != null.

2024-02-01 20:10 UTC, Frilock requested changes
Добрый вечер, еще ряд комментариев

2024-02-01 20:10 UTC, Frilock commented on pom.xml
> +            <version>3.12.0</version>
${commons-lang3.version}

2024-02-01 20:10 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/InMemoryItemStorage.java
> +        if (item.getName() == null) {
отвечая на ваш комментарий, так тогда проверка не правильная, почему при update вы проверяете заполнено или нет старое поле? Вы должны проверять заполнено или нет поле в новом итеме, и если заполнено то тогда обновлять данные, а вы наоборот делаете

2024-02-01 20:10 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/Item.java
> +@Valid
Данную аннотацию не сюда надо вешать а в контроллере

2024-02-01 20:10 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public ItemDto create(@RequestBody ItemDto itemDto, @RequestHeader(OWNER_HEADER) Long ownerId) {
вот сюда, перед ItemDto

2024-02-01 20:10 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        return itemStorage.getItemsBySearchQuery(text).stream()
так сюда прям text.toLowerCase

2024-02-01 20:10 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +@Valid
Анналогично

2024-02-01 20:10 UTC, Frilock commented on src/main/java/ru/practicum/shareit/request/ItemRequest.java
> +@Valid
Анналогично

2024-02-01 20:10 UTC, Frilock commented on src/main/java/ru/practicum/shareit/request/dto/ItemRequestDto.java
> +@Valid
Анналогично

2024-02-01 20:10 UTC, Frilock commented on src/main/java/ru/practicum/shareit/user/InMemoryUserStorage.java
> +        if (user.getName() == null) {
Аналогично

2024-02-01 20:10 UTC, Frilock commented on src/main/java/ru/practicum/shareit/user/User.java
> +@Valid
Анналогично

2024-02-01 20:10 UTC, Frilock commented on src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
> +    public List<UserDto> getUsers() {
Отсуствует owerride

2024-02-02 18:54 UTC, Frilock requested changes
Еще ряд комментариев

2024-02-02 18:54 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/InMemoryItemStorage.java
> +            searchItems = items.values().stream().filter(Item::getAvailable).filter(item -> StringUtils.containsIgnoreCase(item.getName(), text) || StringUtils.containsIgnoreCase(item.getDescription(
Разбейте длинную строку

2024-02-02 18:54 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/InMemoryItemStorage.java
> +        Optional.ofNullable(item.getDescription()).ifPresent(Item -> itemToUpdate.setDescription(item.getDescription()));
ifPresent(itemToUpdate::setDescription)

2024-02-02 18:54 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/InMemoryItemStorage.java
> +        List<Long> deleteIds = items.values().stream().filter(item -> item.getOwnerId().equals(ownerId)).map(Item::getId).collect(toList());
Слишком длинная строка

2024-02-02 18:54 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    @ResponseBody
Лишняя аннотация

2024-02-02 18:54 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    @Valid
Перед ДТО лучше ставить

2024-02-02 18:54 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        ItemDto newItemDto = null;
Перенесите эту логику в сервис

2024-02-02 18:54 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        log.info("PATCH request was received to the endpoint: '/items' to update the item with ID={}", itemId);
Перенесите логику в сервис

2024-02-02 18:54 UTC, Frilock commented on src/main/java/ru/practicum/shareit/user/InMemoryUserStorage.java
> +        if (user.getName() == null) {
Не исправлено

2024-02-03 17:23 UTC, Frilock approved these changes
Принято

2024-02-03 17:23 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public @Valid ItemDto create(@RequestBody ItemDto itemDto, @RequestHeader(OWNER_HEADER) Long ownerId) {
@RequestBody @Valid  ItemDto itemDto

2024-02-17 14:49 UTC, merged